create table public.cliente (
  id_cliente integer generated by default as identity not null,
  nome character varying(100) not null,
  cpf character(11) not null,
  data_nascimento date null,
  email character varying(100) null,
  rua character varying(100) null,
  numero character varying(10) null,
  bairro character varying(60) null,
  cidade character varying(60) null,
  estado character(2) null,
  cep character(8) null,
  constraint pk_cliente primary key (id_cliente),
  constraint uk_cliente_cpf unique (cpf),
  constraint chk_cliente_cep check (
    (
      (cep is null)
      or (length(cep) = 8)
    )
  ),
  constraint chk_cliente_estado check (
    (
      (estado is null)
      or (length(estado) = 2)
    )
  )
) TABLESPACE pg_default;