create table public.pet (
  id_pet integer generated by default as identity not null,
  nome character varying(80) not null,
  especie character varying(50) not null,
  raça character varying(60) null,
  sexo character(1) null,
  peso numeric(5, 2) null,
  data_nascimento date null,
  id_cliente integer not null,
  constraint pk_pet primary key (id_pet),
  constraint fk_pet_cliente foreign KEY (id_cliente) references cliente (id_cliente),
  constraint chk_pet_peso check (
    (
      (peso is null)
      or (peso >= (0)::numeric)
    )
  ),
  constraint chk_pet_sexo check (
    (
      (sexo is null)
      or (sexo = any (array['M'::bpchar, 'F'::bpchar]))
    )
  )
) TABLESPACE pg_default;