create table public.veterinario (
  id_veterinario integer generated by default as identity not null,
  nome character varying(100) not null,
  email character varying(100) null,
  constraint pk_veterinario primary key (id_veterinario)
) TABLESPACE pg_default;