create table public.consulta (
  id_consulta integer generated by default as identity not null,
  data_consulta date not null,
  horario time without time zone not null,
  diagnostico text null,
  observacoes text null,
  id_pet integer not null,
  id_veterinario integer not null,
  constraint pk_consulta primary key (id_consulta),
  constraint fk_consulta_pet foreign KEY (id_pet) references pet (id_pet),
  constraint fk_consulta_veterinario foreign KEY (id_veterinario) references veterinario (id_veterinario)
) TABLESPACE pg_default;