create table public.carteira_vacinacao (
  id_carteira integer generated by default as identity not null,
  data_emissao date not null,
  observacoes text null,
  id_pet integer not null,
  constraint pk_carteira_vacinacao primary key (id_carteira),
  constraint uk_carteira_pet unique (id_pet),
  constraint fk_carteira_pet foreign KEY (id_pet) references pet (id_pet)
) TABLESPACE pg_default;