create table public.telefone_cliente (
  id_telefone_cliente integer generated by default as identity not null,
  telefone character varying(15) not null,
  id_cliente integer not null,
  constraint pk_telefone_cliente primary key (id_telefone_cliente),
  constraint fk_telefone_cliente foreign KEY (id_cliente) references cliente (id_cliente)
) TABLESPACE pg_default;