create table public.telefone_veterinario (
  id_telefone_veterinario integer generated by default as identity not null,
  telefone character varying(15) not null,
  id_veterinario integer not null,
  constraint pk_telefone_veterinario primary key (id_telefone_veterinario),
  constraint fk_telefone_veterinario foreign KEY (id_veterinario) references veterinario (id_veterinario)
) TABLESPACE pg_default;