create table public.especialidade (
  id_especialidade integer generated by default as identity not null,
  nome_especialidade character varying(80) not null,
  constraint pk_especialidade primary key (id_especialidade),
  constraint uk_especialidade_nome unique (nome_especialidade)
) TABLESPACE pg_default;